name       : haskell-libyaml
version    : 0.1.2
release    : 1
source     :
    - https://hackage.haskell.org/package/libyaml-0.1.2/libyaml-0.1.2.tar.gz : 8f42d66f199fcaee255326f8f770d88b0670df56b5eb78002d6058f3a45e97b5
license    : BSD-3-Clause
component  : programming.haskell
summary    : Low-level, streaming YAML interface.
description: |
    Low-level, streaming YAML interface.
builddeps  :
    - pkgconfig(yaml-0.1)
    - haskell-cabal-install
    - haskell-conduit-devel
rundeps    :
    - devel:
        - haskell-conduit-devel
        - yaml-devel
networking : yes
setup      : |
    %cabal_configure -fsystem-libyaml
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
